name: Keep Streamlit App Awake
on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: |
          curl -A "Mozilla/5.0" https://your-app-name.streamlit.app/
